services:
  test_phpv8js_server:
    image: test/phpv8js_server
    container_name: test_phpv8js_server
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./src:/var/www/html

    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - server.env
    networks:
      test_network:
        ipv4_address: 172.77.1.1

networks:
  test_network:
    driver: bridge
    name: test_network
    ipam: # https://docs.docker.com/compose/compose-file/06-networks/#ipam
      driver: default
      config:
        - subnet: 172.77.0.0/16
          ip_range: 172.77.1.0/24
          gateway: 172.77.1.100